name: Join videos

on:
  workflow_dispatch:
  push:
    paths:
      - 'assets/splits/**.mp4'

defaults:
  run:
    working-directory: packages/tools

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: yarn install
      - run: yarn join
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[av] join videos'
