name: Process videos

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'data/sessions/**/*.json'

defaults:
  run:
    working-directory: packages/tools

jobs:
  build:
    runs-on: large
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: sudo apt install nscd ffmpeg xvfb -y
      - run: yarn install
      - run: yarn run:xvfb
        env:
          NEXT_PUBLIC_STUDIO_API_KEY: ${{ secrets.NEXT_PUBLIC_STUDIO_API_KEY }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[av] processed videos'
          add: 'assets/sessions/*.mp4 data/sessions/**/*.json --force'
