name: Split videos

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'data/sessions/**/*.json'

defaults:
  run:
    working-directory: packages/tools

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: sudo apt install -y nscd
      - run: yarn install
      - run: yarn run:split
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[av] split videos'
          add: 'assets/splits/*.mp4 --force'
