name: Upload videos

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'assets/sessions/*.mp4'

defaults:
  run:
    working-directory: packages/tools

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - run: yarn run:upload
        env:
          NEXT_PUBLIC_STUDIO_API_KEY: ${{ secrets.NEXT_PUBLIC_STUDIO_API_KEY }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[new] upload videos'
          add: 'data/sessions --force'
